# Now You Code 3: Area and Circumfrence

In this assignment you are tasks with writing a program which inputs the radius of a circle, and outputs the circumfrence and area of that circle. Feel free to lookup the formulas online. 

We will use the **Write - Refactor - Test - Rewrite** approach to complete the final solution which uses functions.

**NOTE** `import math` then use `math.PI` to get the value of Pi https://en.wikipedia.org/wiki/Pi

## Step 1: Write

Here's the algorihm of this program. Write the solution in Python.

```
    input radius as a float
    calculate circle area
    calcuate circle circumfrence
    print radus, area, circumfrence
```

Example run:

```
Enter Radius: 1
A circle with radius 1.000000 has area 3.141593 and circumfrence 6.283185
```


In [1]:
import math
## TODO: Write the solution here Step 1
radius = float(input("Enter the raidus: "))
area = math.pi * radius*radius
circumfrence = math.pi*2*radius
print("Radius is: %f Area is: %f Circumfrence is: %f"%(radius, area, circumfrence))

Enter the raidus: 1
Radius is: 1.000000 Area is: 3.141593 Circumfrence is: 6.283185


## Step 2: Refactor

Next we need to refactor the `area` and `circumfrence` logic into functions. 

- `CircleArea()` has one input a `radius` and returns the `area` as output.
- `CircleCircumfrence()` has one input a `radius` and returns the `circumfrence` as output. 


In [17]:
## Step 2: Refactor into two functions def CircleArea... and def CircleCircumfrence
def CircleArea(radius):
    import math
    area = math.pi*radius*radius
    return area

def CircleCircumfrence(radius):
    import math
    circumfrence = math.pi*2*radius
    return circumfrence

## Step 3: Test 

Time to test. Write two tests, once for each function
```
WHEN radius=1 We EXPECT CircleArea(radius) to return 3.141593 
WHEN radius=1 We EXPECT CircleCircumfrence(radius) to return 6.283185
```

Make sure you call the function to get the actual, just like in the coding lab. 

NOTE: If its accurate to 4 decimal places, that's sufficient. The test values might be different because of how the "%f" format code works.

In [19]:
# Step 3: Write tests.
radius = 1.0
CircleArea(radius)

CircleCircumfrence(radius)


6.283185307179586

## Step 4: rewrite the program to use the function

Finally re-write the original program, but call the functions. 


In [20]:
## Step 4: Write program here from the algorithm above
radius = float(input("What is the radius? ")
CircleArea(radius)
CircleCircumfrence(radius)
               
               #I don't know what's wrong here because it worked before and I went back to make sure I did it

SyntaxError: invalid syntax (<ipython-input-20-7aa6d0b07f33>, line 3)

## Step 6: Questions

1. Provide 3 advantages for programming a user function in your code like `CircleArea`  or `CircleCircumfrence`
1)if the function is correct you don't have to worry about an error
2)if you plan on doing the same action multiple times
3)it takes up less space than writing the steps every time
2. If we want to guarantee our `CircleCircumfrence` function is 100% accurate, what is the minimum number of test cases must we provide in step 3?
8:
valid positive number
valid float
negative number
negative float
0
letter
word
symbol


## Reminder of Evaluation Criteria

1. What the problem attempted (analysis, code, and answered questions) ?
2. What the problem analysis thought out? (does the program match the plan?)
3. Does the code execute without syntax error?
4. Does the code solve the intended problem?
5. Is the code well written? (easy to understand, modular, and self-documenting, handles errors)
